smb2pdu.c
fix side effects (smb2.create.mkdir-dup, multi)
to avoid error return in smb2.create.mkdir-dup,
check NT_STATUS_NOT_A_DIRECTORY only if named stream exists.
smb2.create.mkdir-dup gives requests whose FileAttributes is 0x80
and CreateOptions is FILE_DIRECTORY_FILE.
modify NT_STATUS_OBJECT_NAME_COLLISION condition in order to pass
smb2.create.multi that sends multiple create requests
with same names and CreateOptions=0.
=> cifsd: fix side effects (smb2.create)

fh.c, fh.h, glob.h, misc.c, oplock.c, smb1pdu.c, smb2pdu.c, srv.c, vfs.c
request to merge with stable patches.
=> Cifsd next

glob.h, smb2pdu.c, vfs.c
cifsd: fix some get_info and set_info implemenations
=> cifsd: fix some get_info and set_info implemenations

auth.c, cifsacl.c, connect.c, export.c, fh.c, misc.c, smb2pdu.c, unicode.c
These patch set are fixes for SVACE and KASan issues.
Please check cifsd-tools also.
=> Fix svace kasan

connect.c, smb2pdu.c
cifsd: remove an unnecessary debug message.
cifsd: send pending response before handling request.
Please check cifsd-tools also.
=> Notify add notid

fh.c
=> cifsd: add a NULL check for fp->f_opinfo

smb2pdu.c
rollback and disable smb2 notify code because of some side effects.
=> cifsd: disable smb2 notify code

smb1pdu.c
Signed-off-by: Namjae Jeon <namjae.jeon@protocolfreedom.org>
=> cifsd: fix incorrect fp check in find_first()

smb2pdu.c
=> cifsd: fixed kernel oops by .socket file

smb2pdu.c
=> cifsd: fixed kernel oops by NULL filp

glob.h, smb1pdu.c, smb2pdu.c
Fix some SMBv1 trans2 bugs which are found with Samba torture's search testcases.
=> Fix some SMBv1 trans2 bugs

smb2pdu.c, smb2pdu.h
failed MS testsuite: NegotiateTestCaseS795
=> cifsd: modified SMB2 error response

Makefile, buffer_pool.c, buffer_pool.h, connect.c, fh.c, glob.h, misc.c, oplock.c, smb1pdu.c, smb2pdu.c, srv.c, vfs.c
Some cleanups: mostly buffers and flags clean ups. A switch to a new buffer pool API.
=> First part of cleanups.

srv.c
=> cifsd: delete response caches leftovers

Makefile, asn1.c, auth.c, buffer_pool.c, connect.c, export.c, export.h, fh.c, fh.h, glob.h, misc.c, netlink.c, oplock.c, oplock.h, server.c, smb1ops.c, smb1pdu.c, smb2ops.c, smb2pdu.c, smb2pdu.h, srv.c, transport.c, transport.h, vfs.c
Work in progress. These are just the first steps.
=> Factor out TCP transport layer

smb2pdu.c
The SMB2_PREAUTH_INTEGRITY_CAPABILITIES and SMB2_ENCRTRYPTION_CAPABILITIES
context are specified in an 8-byte aligned SMB2 NEGOTIATE response.
The CipherCount field MUST be 1, so the Ciphers[0] is only used in the
smb2_encryption_neg_context structure.
=> cifsd: hotfix a byte align for smbclient connection fail

fh.c
a) Do not perform GFP_KERNEL allocation under mfp_hash_lock spinlock,
because GFP_KERNEL can schedule.
b) Do not keep mfp_hash_lock while we init a new mfp
c) Free a newly allocated mfp when we cant init it
d) Split function into fast and slow path (we need to re-do hash
lookup from slow path to make sure we didn't race with another
open()).
=> cifsd: fix scheduling from atomic context

transport.c
Protect tcp_conn_list with a readers-writer lock. We don't have
many reader sides yet, but will have more in the future so having
non-blocking readers will, probably, be advantageous.
=> cifsd: use readers-writer lock in cifsd_tcp

smb2pdu.c
1. When the lease feature is truned off, any directory has not been opened
using a Win7 client owing to the STATUS_OBJECT_NAME_INVALID error.
The returned ENOENT error code from smb2_find_context_vals need to be
cleared to 0 for next processing.
2. Refactoring the redundant context error checking code
=> cifsd: fix STATUS_OBJECT_NAME_INVALID error

smb1pdu.c
modified the wrong code because of compatibility with windowsXP.
Signed-off-by: Gibeom Kim <gibeomii.kim@samsung.com>
=> cifsd: modified the wrong code because of compatibility with windowsXP

smb2pdu.c
=> cifsd: use CIFSD_NO_FID for compound FID and PFID

smb1pdu.c
Do not do smb_query_info() in PIPE shares, and return dummy attrs
instead:
[<ffffffc0002cea60>] strlen+0x10/0x90
[<ffffffbffc0911f0>] convert_to_unix_name+0x208/0x22b0 [cifs_server]
[<ffffffbffc097c9c>] smb_query_info+0x2c/0x158 [cifs_server]
[<ffffffbffc0a05f4>] cifsd_ipc_init+0x254/0x7e8 [cifs_server]
[<ffffffc0000aa688>] process_one_work+0x120/0x3b0
[<ffffffc0000aaa3c>] worker_thread+0x124/0x4f8
[<ffffffc0000afe70>] kthread+0xd8/0xf0
=> cifsd: return dummy attrs for pipe shares

fh.c
=> cifsd: null out stream name

cifsd_server.h, smb2pdu.c
=> cifsd: add hide dot files parameters

smb2pdu.c
some application(potableapp) can not run on cifsd share because only NTFS
handle security setting on windows. So Although local fs(EXT4 or F2fs, etc)
is not NTFS, cifsd should show share as NTFS. Later, If needed, we can add
fs type(s) parameter to change fs type user wanted.
=> cifsd: make default fstype as NTFS

smb_common.c
=> cifsd: disable SMB 2.002 in insecure builds

asn1.c, auth.c, buffer_pool.c, buffer_pool.h, cifsacl.c, fh.c, mgmt/tree_connect.c, mgmt/user_session.c, misc.c, misc.h, netmisc.c, oplock.c, oplock.h, server.c, smb1misc.c, smb1pdu.c, smb1pdu.h, smb2pdu.c, smb2pdu.h, smb_common.c, transport_tcp.c, unicode.h, vfs.c, vfs.h
Signed-off-by: Rosen Penev <rosenp@gmail.com>
Tested under OpenWrt.
=> treewide: Run through checkpatch.pl and fix errors.

smb2pdu.c
[3-51.9732] [<c0351854>] (depot_fetch_stack) from [<c0185fbc>] (print_track+0x90/0xb4)
[3-51.9732] [<c0185f2c>] (print_track) from [<c0187190>] (print_tracking.part.13+0x3c/0x68)
[3-51.9732]  r6:e5ae1b80 r5:e4501cc0 r4:e195d680
[3-51.9732] [<c0187154>] (print_tracking.part.13) from [<c01872f8>] (print_trailer+0x13c/0x1b8)
[3-51.9732]  r5:e4501cc0 r4:e195d680
[3-51.9732] [<c01871bc>] (print_trailer) from [<c0187448>] (check_bytes_and_report+0xd4/0xf0)
[3-51.9733]  r7:e5ae1b80 r6:e4501cc0 r5:e195d880 r4:e195d884
[3-51.9733] [<c0187374>] (check_bytes_and_report) from [<c01875d0>] (check_object+0x16c/0x234)
[3-51.9733]  r9:e35a6000 r8:e35a7db4 r7:e5ae1b80 r6:000000cc r5:e195d680 r4:e4501cc0
[3-51.9733] [<c0187464>] (check_object) from [<c0187c20>] (free_debug_processing+0x16c/0x344) …
=> cifsd: fix memory overrun issue

smb1pdu.c
=> cifsd: add missing cifsd_fd_put at several places in smb1pdu

glob.h
=> cifsd: release 2.0.4 version

README.md
=> ksmbd: update README file

glob.h
=> ksmbd: release 3.1.1 version
