- smb1pdu.c
- smb2pdu.c
1. Fix FILE_BOTH_DIRECTORY_INFORMATION to response a short name
as FILEID_BOTH_DIRECTORY_INFORMATION does.
2. Fix FILE_ALTERNATE_NAME_INFORMATION case to get short name
not from absolute path but from file name itself
like cifsd and Windows7 directory query implementations.
3. Remove a duplicated doubling of short name length.
4. Modify full name length not to count NULL as Windows7 does.
> cifsd: fix short_name fails from smb2.dir.one TC

- glob.h
- smb1pdu.c
- smb2pdu.c
cifsd: fix smb2.dir.modify failures and modify the way to get xattr values
> cifsd: fix smb2.dir.modify failures and modify the way to get xattr values

- smb2pdu.c
fix a side effect of 7df698f0f4ec9c936e2bea67e631c8a7efb19708.
get FileAttributes value after stat is filled.
> cifsd: fix a side effect of 7df698f0f4ec9c936e2bea67e631c8a7efb19708.

- smb2pdu.c
fix smb2.create.open and delete.
smb2_get_info_file function gave inaccurate Atrributes value
for FileInfoClasses but FILE_BASIC_INFORMATION.
fix it to respond a valid Attributes value.
> cifsd: fix some smb2.create failures.

- glob.h
- smb2pdu.c
- vfs.c
1. make setinfo not to allow to change non-directory file's attributes
into ATTR_DIRECTORY.
2. implement set_info FILE_POSITION_INFORMATION case.
> cifsd: fix some smb2.setinfo failures

- fh.c
- fh.h
- smb2pdu.c
fix some FileInfoClass to make NumberOfLinks and DeletePending
give valid values when get_info is requested.
when FileDispositionInformation's DeletePending is 0,
clear S_DEL_ON_CLS bit of mfp->m_flags.
Signed-off-by: Namjae Jeon <namjae.jeon@protocolfreedom.org>
> cifsd: fix nlink and delete_pending

- misc.c
- smb2pdu.c
fix a side effect by storing file attributes value in xattr.
fix smb2open to destroy xattr only when CreateDisposition is
FILE_SUPERSEDE.
fix construct_xattr_stream_name to do kmalloc only essential size.
> cifsd: fix smb2 getinfo FILE_FULL_EA_INFORMATION

- smb2pdu.c
make ctime value not to be changed by storing xattr value.
by doing so, ctime is not changed when file_info->CtreationTime
is zero.
> cifsd: hack to give valid ctime value

- fh.c
- glob.h
- smb2pdu.c
- vfs.c
fix next_offset to get valid value.
fix smb2_set_ea function to delete xattr when EaValueLength is zero.
When setting EA information, if EaValueLength is zero,
then the given EaName and its current value are deleted
from the given file.
> cifsd: fix torture setinfo failures

- smb2pdu.c
- smb2pdu.h
implement setinfo FileAllocationInformation
which fallocates or truncates opened file's allocated size
based on current i_blocks and AllocationSize requested.
because FileAllocationInformation is only for setinfo,
getinfo FileAllocationInformation is deleted.
> cifsd: implement setinfo FileAllocationInformation

- smb2pdu.c
- smb2pdu.h
Add get_info FS_CONTROL_INFORMATION.
Modify some file_info_classes' sizes based on a smb2 torture TC and
Windows 7. it needs to consider variable-sized field's minimum size.
> cifsd: fix some getinfo torture failures

- fh.c
alloc_large_system_hash function is not exported. so when building module,
facing build failures or insmod failure.
So this patch add initializing code of master fp hash table instead of
using alloc_large_system_hash()
Signed-off-by: Namjae Jeon <namjae.jeon@protocolfreedom.org>
> cifsd: fix insmod failure when building module

- export.h
- glob.h
- netlink.c
- netlink.h
- smb2pdu.c
- smb2pdu.h
This patch is to add a smb2_notify implementation into cifsd.
When a smb2 notify request is received from a client,
an inotify-request is sent to user-space.
when an event, which matches with completion filter
in the notify request packet, occurs, user daemon send
a netlink event to kernel-space with notify response information.
Then kernel send a notify response packet to the client
with the information.
Please check cifsd-tools' pull-request also.
> cifsd: implement smb2_notify command

- export.h
- glob.h
- netlink.c
- smb2pdu.c
When kernel get multiple notify requests for a file,
put them in fp->queue and send it to user space daemon one by one.
It ensures that user space daemon handles only one inotify request
for a file at a time.
** Please check cifsd-tools repo also.
> cifsd: support multiple sessions

- smb2pdu.c
Check valatile_id instead of fp to avoid case that
tries to delete invalid fid from session fid table.
Remove unnecessary NULL-assignments.
> cifsd: fix an oops

- vfs.c
kernel NULL pointer dereference at
[0-124.8900] [<c02282c8>] (get_logical_sector_size) from [<c0243748>] (smb2_get_info_filesystem+0x424/0x618)
[0-124.8901] [<c0243324>] (smb2_get_info_filesystem) from [<c0243af8>] (smb2_query_info+0x1bc/0x2f4)
The inode->i_sb->s_bdev was NULL on tmpfs.
> cifsd: fixed oops from getting logical sector size

- glob.h
- smb1pdu.c
- smb2pdu.c
Fix some bugs which are found with torture search testcases.
Support search patterns including wildcards
and Reserve dot/dotdot entries in head of response.
> cifsd: fix some SMBv1 search bugs

- Kconfig
We need to select CONFIG_KEYS to enable linux/key-type.h, otherwise
we get build errors:
cifsacl.c:74:52: warning: ‘struct key_preparsed_payload’ declared inside parameter list will not be visible outside of this definition or declaration
cifs_idmap_key_instantiate(struct key *key, struct key_preparsed_payload *prep)
^~~~~~~~~~~~~~~~~~~~~
cifsacl.c: In function ‘cifs_idmap_key_instantiate’:
cifsacl.c:86:10: error: dereferencing pointer to incomplete type ‘struct key_preparsed_payload’
if (prep->datalen <= sizeof(key->payload)) {
^~
cifsacl.c:86:33: error: dereferencing pointer to incomplete type ‘struct key’
if (prep->datalen <= sizeof(key->payload)) {
^~
cifsacl.c: At top level:
cifsacl.c:121:15: error: variable ‘cifsd_idmap_key_type’ has initializer but incomplete type
static struct …
> Kconfig: add CONFIG_KEYS dependency

- glob.h
- srv.c
There is no need to have 10 goto labels in smb_initialize_mempool().
mempool_destroy() and kmem_cache_destroy() will not dereference and
destroy a NULL mempool or cache. Thus we can call smb_free_mempools()
for error handling in smb_initialize_mempool().
Also, make smb_free_mempools() static.
It saves us some instructions, BTW:
$ ./scripts/bloat-o-meter fs/cifsd/cifsd.o fs/cifsd/cifsd.o.new
add/remove: 0/0 grow/shrink: 0/2 up/down: 0/-220 (-220)
Function                                     old     new   delta
init_smb_server                              666     556    -110
init_module                                  666     556    -110
> srv: simplify error handling in smb_initialize_mempool()

- srv.c
commit "net: make getname() functions return length rather than
use int* parameter" has dropped some arguments from a number of
net/ functions. We are using one of those functions, namely,
kernel_getpeername() - which now requires only 2 params.
This is quite annoying, so make a temp (!) fix, which must be
dropped when we will push cifsd upstream.
> srv: work-around 4.16 build error

- smb2pdu.c
- srv.c
memcpy(version_string, "1.1.0", STRING_LENGTH) copies STRING_LENGTH
bytes from the source buffer. The problem is that our source buffer
is just strlen("1.1.0") bytes long, while STRING_LENGTH is 28 bytes.
So we copy memory beyond the source buffer, which, in theory, can
leak some important information.
> smb2pdu: fix invalid memcpy() memory access

- srv.c
conn->sess_count++ when smb2_sess_setup.
It should be decreased when the session is deleted.
> cifsd: fixed the session count mismatch

- export.c
- export.h
Tweak chktkn():
a) do not duplicate memory (strsep() modifies
original string)
b) rename it to conflist_search(), because the functions, basically,
checks if a key exists in a list (tabs, commas, spaces separated
smb.conf list)
$ size cifsd.o cifsd.o.new
text	   data	    bss	    dec	    hex	filename
228177	   7948	    257	 236382	  39b5e	cifsd.o
227951	   7948	    257	 236156	  39a7c	cifsd.o.new
> cifsd: slightly improve user/share validation

- Makefile
- auth.c
- export.c
- export.h
- management/user.c
- management/user.h
- netlink.c
- smb1pdu.c
- smb2pdu.c
This patch is a first bit of resource management rework. In this patch
we change we way we manage users. The bits of user management now moved
to a new file - user_management.c, which encapsulates all the internal
details, which previously were spread across the system.
First change,
- we used to have a global list of all registered users
This forced us to do costly for_each() lookups in search for user
name match, which is O(n) operation. The more users we have - the
longer it takes to logon and so on.
Besides, we should not export users list. It's a very internal detail
which must be known only to user management code.
We now use hash table.
Second change,
- our user list was not protected from concurrent modifications.
It was perfectly possible to have CPU1 iterating the list, while …
> cifsd: initial version of a new user management

- smb2pdu.c
MS testsuite: Fileserver > NegotiateTestCaseS2219
In case of Dialect: 0x02ff in SMB2 negotiate request, the STATUS_NOT_SUPPORTED response should be sent.
It also should consider the SMB1 negotiate request with dialects.
> cifsd: fixed SMB negoiate response for the wildcard dialect revision

- smb2pdu.c
> cifsd: fixed SMB negoiate response for the wildcard dialect revision
>
> MS testsuite: Fileserver > NegotiateTestCaseS2219
>
> In case of Dialect: 0x02ff in SMB2 negotiate request, the STATUS_NOT_SUPPORTED response should be sent.
> It also should consider the SMB1 negotiate request with dialects.
And, it should be sent with an SMB2 error response.
> cifsd: refixed SMB2 negotiate response for the wildcard dialect revision

- smb2pdu.c
MS testsuite: Fileserver > NegotiateTestCaseS2133
This testcase sends the SMB2 request with the wrong dialect count.
The SMB2 error response should be sent with STATUS_INVALID_PARAMETER (0xc000000d).
> cifsd: fixed the SMB2 negotiate response to the wrong dialect count

- smb2pdu.c
MS testsuite > FileServer > NegotiateTestCaseS1698
First, SMB negotiate with Dialect: SMB 2.???
and then, SMB2 negotiate with Dialect count = 0.
The cifsd should respond as 0x02ff dialect and INVALID_PARAMETER.
> cifsd: fixed SMB/SMB2 negotiation with wildcard & wrong dialects

- smb1pdu.c
- smb1pdu.h
This patch set is to fix a bug and no-implementation erros
which were found with torture raw.search.
A find_first bug is fiexed and some missed information levels for
trans2 commands are added.
Taeyang Mok (3):
cifsd: add an alias for an information level
cifsd: add 4 informaion levels
cifsd: ignore dot_dotdot entries
smb1pdu.c | 136 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--
smb1pdu.h |  30 ++++++++++++++
2 files changed, 162 insertions(+), 4 deletions(-)
-- 
1.9.1
> [PATCH 0/3] add some information levels for trans2 commands

- fh.c
- fh.h
- glob.h
- misc.c
- smb1pdu.c
- smb2pdu.c
- vfs.c
We don't support 3.10, so we can drop some of LINUX_VERSION_CODE
if-s. The remaining if-s are really ugly, we need to move out of
the core code as many of them as possible and put them into macros
or small one-liner helper functions.
> cifsd: drop some of unused LINUX_VERSION_CODE if-s

- vfs.c
> cifsd: fix a typo in kern_path_create() call

- smb1pdu.c
Some clients like Windows may have additional padding.
So when handling RPC commands, add padding to pipedata pointer.
Signed-off-by: Gibeom Kim <gibeomii.kim@samsung.com>
> cifsd: fix a RPC command error

- oplock.c
- server.c
- smb1pdu.c
- smb2pdu.c
- transport.c
- transport.h
The patch set adds a simple tcp_conn API extension to address some of
common mistakes, e.g. missing ->req_runing decrement.
> tcp_conn API extension

- buffer_pool.c
- buffer_pool.h
- fh.c
- fh.h
- glob.h
- misc.c
- oplock.c
- oplock.h
- server.c
- smb1pdu.c
- smb1pdu.h
- smb2pdu.c
- smb2pdu.h
- transport.c
- transport.h
- vfs.c
Rename struct smb_work to cifsd_work.
> cifsd: rename smb_work

- fh.c
- fh.h
- glob.h
- misc.c
- smb2pdu.c
- vfs.c
find_fp_using_inode() belongs to fh.c and fh.h. Move it out
of misc.c and glob.h (which must die).
> cifsd: move find_fp_using_inode()

- smb1pdu.c
removed PID check from read write function
because FID check is specified, but PID check is not
specified From the spec in read write function.
This issue was observed during
compatibility testing with Windows XP.
Signed-off-by: Gibeom Kim <gibeomii.kim@samsung.com>
> cifsd: removed PID check from read write function

- smb2pdu.c
This appears to be a "normal" windows behaviour
[ 4151.582446] kcifsd: smb2_open:2411: Can't open dir /media/edev/share1, request is to open file : 60
[ 4151.583742] kcifsd: smb2_open:2411: Can't open dir /media/edev/share1, request is to open file : 60
[ 4151.597687] kcifsd: smb2_open:2411: Can't open dir /media/edev/share1, request is to open file : 68
[ 4152.194573] kcifsd: smb2_open:2411: Can't open dir /media/edev/share1, request is to open file : 60
[ 4152.195409] kcifsd: smb2_open:2411: Can't open dir /media/edev/share1, request is to open file : 60
[ 4152.207293] kcifsd: smb2_open:2411: Can't open dir /media/edev/share1, request is to open file : 68
[ 4153.196053] kcifsd: smb2_open:2411: Can't open dir /media/edev/share1, request is to open file : 60
[ 4153.197290] kcifsd: …
> cifsd: downgrade "cant open dir" to a debug message

- mgmt/share_config.c
Windows does not tolerate upper/lower-case share names and treats
them equally. So should we. cifsd-tools will convert all share names
to a lower case, but we need to do the same on the kernel side as
well - to make share cache usable.
Reported-by: Namjae Jeon <namjae.jeon@protocolfreedom.org>
> cifsd: convert all net share name to lowercase

- server.c
- server.h
> cifsd: drop duplicate config options, and do not leak memory on module exit

- export.h
- glob.h
- misc.c
- server.c
Usage example:
modprobe cifsd cifsd_debugging=2
or
echo 2 > /sys/module/cifsd/parameters/cifsd_debugging
> cifsd: add cifsd_debugging module param

- auth.c
- encrypt.c
- encrypt.h
- fh.c
- glob.h
- smb2pdu.c
SMB1 spec says the following:
https://msdn.microsoft.com/en-us/library/ff470197.aspx
- The FID MUST be a 16-bit opaque value.
- The FID MUST be unique within a specified client/server SMB
connection.
- The FID MUST remain valid for the lifetime of the SMB connection
on which the open request is performed, or until the client sends
a request to the server to close the FID.
- Once a FID has been closed, the value can be reused for another
create or open request.
- The value 0xFFFF MUST NOT be used as a valid FID. All other possible
values for FID, including zero (0x0000) are valid. The value 0xFFFF
is used to specify all FIDs or no FID, depending upon the context in
which it is used.
SMB2 spec does not define any limitations on FID value range: …
> cifsd: start fileid from 0

- fh.c
- fh.h
- smb1pdu.c
init_fidtable() uses hard-coded value, while the rest of the
functions use CIFSD_START_FID. Set CIFSD_START_FID to 0 and
use it in init_fidtable().
> cifsd: use CIFSD_START_FID in fh

- transport_ipc.c
The macro is perfetctly fine, but our static analyzer doesn't like
it:
Arithmetic operations on /void */ is a GNU C extension, which
defines the /sizeof(void)/ to be 1.
> cifsd: rewrite CIFSD_IPC_MSG_PAYLOAD to make static analyzer happy

- smb2pdu.c
Fix: compound request  tree_conn, write
If we have denied tree_conn, then work->tcon is NULL; but we don't
recheck ->tcon when we process next command in compound request and
end up NULL dereferencing ->tcon. Return a porper negative error
code from tree_connect and abort further compound request processing.
BUG: unable to handle kernel NULL pointer dereference at 0000000000000008
PF error: [normal kernel read fault]
PGD 0 P4D 0
Oops: 0000 [#1] PREEMPT SMP PTI
CPU: 7 PID: 251 Comm: kworker/7:4 Tainted: G        W         4.20.0-rc4-next-20181128-dbg-00005-gd6f00891d986-dirty #3009
Workqueue: events handle_cifsd_work [cifsd]
RIP: 0010:smb2_write+0x10f/0x2f0 [cifsd]
Code: 00 00 00 00 0f c8 83 c0 10 0f c8 41 89 04 24 31 c0 48 83 c4 18 5b 5d 41 5c 41 5d 41 5e 41 5f c3 48 8b 45 38 4d 89 e5 48 …
> cifsd: fix smb2_write NULL pointer dereference

- server.c
This is a patch to rollback codes.
In case of a notify task that is currently being implemented, it will be
set to asynchronous and wait for any file change events. Therefore, the
locking should be released before cmds->proc(), so that the next commands
from clients can be processed.
int smb2_notify(struct cifsd_work *cifsd_work)
{
...
setup_async_work();
smb2_send_interim_resp();
// waiting for notification here
cifsd_file_notify_wait();
...
}
> cifsd: rollback to unlock codes for waiting task

- transport_ipc.c
> cifsd: log ipc_server_config_on_startup() error

- smb2pdu.c
linux locking supports byte range up to 2^31, But window allowed lock
range up to 2^63. and cifsd return invalid range range error response with
such request. But this is causing write failure from some application.
They try to write after locking with 2^63 range. cifsd fakes success return
by changing byte lock range.
> cifsd: fake success return by changing byte lock range

- smb1pdu.c
We're forgetting to release allocated resources before we
return AndXCommand from smb_tree_connect_andx().
> cifsd: fix a bunch of memleaks in smb_tree_connect_andx()

- smb2pdu.c
don't force signing enable with SMB3.x.
> cifsd: don't force signing enable with SMB3.x

- server.c
It seems that **.class_groups** was not introduced in kernel [v4.9.0](https://elixir.bootlin.com/linux/v4.9/source/include/linux/device.h#L364) but in [v4.10.0](https://elixir.bootlin.com/linux/v4.10/source/include/linux/device.h#L365)
Commit to the kernel that introduced **.class_groups**
https://github.com/torvalds/linux/commit/ced6473e7486702f530a49f886b73195e4977734
> cifsd: Fix compilation for v4.9.0 linux kernels

- smb2pdu.c
> ksmbd: fix read caching buffer size as max_read_size

- glob.h
Major changes are:
- Add ACLs support
- Add Kerberos support
- Add query info/query dir/statfs for smb3.1.1 posix extension.
- Fix warnings from checkpatch.pl
- Fix racy issue reported and warnings from KSAN by OpenWRT.
> cifsd: release 3.3.0 version

- glob.h
Major change are:
- Fix insmod failure if CONFIG_FS_POSIX_ACL is not set in config.
> cifsd: release 3.3.1 version

- glob.h
Major changes are:
- add support for SMB3 multichannel.
- add support for FSCTL_DUPLICATE_EXTENTS_TO_FILE.
- add support for AES256 encryption.
- rename cifsd to ksmbd.
- use generic asn1 decoder instead of own one.
- remove cache read/trans buffer feature.
- fix several bugs.
- cleanup codes from review comments.
> ksmbd: release 3.4.0 version
